### ISSUE TITLE
[COPX]Ροδος + Ηρακλειο

### ISSUE THREAD

**Issue by tasosb** [tasosb/hvacc-sector-file#15]
**Description**
Ροδος: LAKAD, NILAS,IRBAX ,για INBOUND ειναι FL180, για OUTBOUND FL170

 XAVIS για INBOUND εχει FL130 αντι για FL110

**Additional context**
Add any other context here.

**Comment by tasosb** [comment]
Αλλαγη για 1906

**Comment by marks87** [comment]
Rodos TMA upper boundary FL155

**Comment by marks87** [comment]
@tasosb check

**Comment by tasosb** [comment]
![εικόνα](https://user-images.githubusercontent.com/18355854/60549514-ca062400-9d2d-11e9-94e7-c43d63671b0a.png)
μενουμε στα τωρινα copx
