### ISSUE TITLE
Waypoint EPIRU to be removed. No longer exists

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#19]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you suggest**
A clear and concise description of what you want to change.

**Additional context**

**Comment by tasosb** [comment]
**Fixed**
Alias: `..FIX-LGKR .FF OLGAT TIGRA NOSTO LATAN IDIMI RIPID MALED PARNA NIKRO PITAS BEDEX DIREX`
EPIRU & BETAK Removed
Added BEDEX

**Comment by tasosb** [comment]
GLO COPX also removed
