### ISSUE TITLE
[COPX] and waypoint ATLAN to be removed. No longer exists

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#20]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you suggest**
A clear and concise description of what you want to change.

**Additional context**

**Comment by tasosb** [comment]
Pending AIRAC release from aerosoft

**Comment by tasosb** [comment]
Υπάρχει ακόμα στο νεο AIRAC Release της aerosoft και συγκεκριμενα:

- Airway A14

**Comment by tasosb** [comment]
το ATLAN οντως δεν υπαρχει πλεον ως σημειο (ουτε στο airway) αλλα το εχει ξεχασει η aerosoft μαλλον

copx removed, no star/sid from lgsr 
![εικόνα](https://user-images.githubusercontent.com/18355854/56912298-aae1e080-6ab7-11e9-8426-ea2ff5ff8b54.png)
