### ISSUE TITLE
[COPX] waypoint RILIN outbound FL240, inbound FL170

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#21]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you suggest**
A clear and concise description of what you want to change.

**Additional context**

**Comment by tasosb** [comment]
Remains FL160 (from ATC Recording)
Το inbound δεν θα οριστει λογω αναχωρησεων (καλυτερα να γινεται συννενοηση LGGG->LGAV APP)
