### ISSUE TITLE
[COPX] waypoint AGAPU inbound LGMK , FL210

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#22]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you suggest**
A clear and concise description of what you want to change.

**Additional context**

**Comment by tasosb** [comment]
![εικόνα](https://user-images.githubusercontent.com/18355854/56921973-cc4ec680-6acf-11e9-9392-07488387f3d8.png)
FIXED
