### ISSUE TITLE
STAR for LGPZ MALED1B instead of MALED1A for 07L

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#23]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you suggest**
A clear and concise description of what you want to change.

**Additional context**

**Comment by tasosb** [comment]
FIXED
![εικόνα](https://user-images.githubusercontent.com/18355854/56923888-513bdf00-6ad4-11e9-8428-9494fec6c732.png)
