### ISSUE TITLE
[COPX] NIKTI inbound LGKV FL150

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#24]
**Description**

**Additional context**
Add any other context here.

**Comment by tasosb** [comment]
![Screenshot_20190429-180131_Samsung Internet](https://user-images.githubusercontent.com/18355854/56922021-eee0df80-6acf-11e9-8789-fc3f178ece53.jpg)

**Comment by tasosb** [comment]
FIXED
