### ISSUE TITLE
[COPX] IRBEG & UVRIT check inbound and outbound _LGGGRDS sector not the correct one.

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#29]
**Description**

**Additional context**
Add any other context here.

**Comment by tasosb** [comment]
![εικόνα](https://user-images.githubusercontent.com/18355854/57194991-07307e80-6f56-11e9-907e-458153094312.png)
![εικόνα](https://user-images.githubusercontent.com/18355854/57195001-11527d00-6f56-11e9-9f47-2fbe4bba7454.png)

**Comment by tasosb** [comment]
![εικόνα](https://user-images.githubusercontent.com/18355854/57195038-8f168880-6f56-11e9-9d9e-2cb3f789697f.png)
FIX 
![εικόνα](https://user-images.githubusercontent.com/18355854/57195045-a35a8580-6f56-11e9-9209-7b6fb78a40e3.png)
![εικόνα](https://user-images.githubusercontent.com/18355854/57195051-b2413800-6f56-11e9-8da2-9e496d42f14e.png)

**Comment by tasosb** [comment]
revert to LGGGRDS145-155

**Comment by tasosb** [comment]
Αναβολη: Θα το ψαξουμε μετα το 1906

**Comment by marks87** [comment]
LGGGMIL
