### ISSUE TITLE
[SECTORIZATION] LGMD_TSL not correct

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#31]
correct sector is pic no1 . wrong is pic no2
![Screenshot_1](https://user-images.githubusercontent.com/19704019/57065949-a4c84b80-6cd3-11e9-9d62-f6771d841999.png) pic1
![Screenshot_2](https://user-images.githubusercontent.com/19704019/57065959-a8f46900-6cd3-11e9-953e-f91d81dd3ef4.png) pic2

**Comment by marks87** [comment]
LGMD_CTR,
LGMD_K_CTR, 
LGMD_E_CTR,
LGMD_T_CTR


SECTOR LGGGTSL, LGGGKVL
