### ISSUE TITLE
[BUG] BAVES FL 180

### ISSUE THREAD

**Issue by tasosb** [tasosb/hvacc-sector-file#4]
**Describe the bug**
BAVES COPX LGIRAPP->LGGGMIL FL180

**To Reproduce**
Steps to reproduce the behavior: X

**Comment by marks87** [comment]
AIP 2.1.5.4 IRAKLION TMA ΕΩΣ FL155 και περιορισμός απο gng

**Comment by tasosb** [comment]
**BT:** Fixed
