### ISSUE TITLE
[COPX] LOKNA inbound LGRP FL170. oubound FL160

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#40]
**Description**

**Additional context**
Add any other context here.

**Comment by marks87** [comment]
Rodos TMA upper boundary FL155 @tasosb

**Comment by tasosb** [comment]
![εικόνα](https://user-images.githubusercontent.com/18355854/60549551-e609c580-9d2d-11e9-8c49-e4e88ddb1359.png)
won't fix
