### ISSUE TITLE
[BUG] LGAV_APP Title

### ISSUE THREAD

**Issue by tasosb** [tasosb/hvacc-sector-file#51]
**Describe the bug**

Athens arrival -> Athinai Approach

**Comment by nakoale** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/19704019/62763417-31816300-ba94-11e9-81db-8eb0cfa2288b.png)

**Comment by tasosb** [comment]
Athinai-Athens Approach
Fixed

**Comment by tasosb** [comment]
απο πανω ειναι αυτο
![εικόνα](https://user-images.githubusercontent.com/18355854/63442031-0f47f780-c43b-11e9-87ac-2093c3957f49.png)
τωρα αν δεν ειναι ανοιχτο το DEPARTURE κ το director μηπως γινεται athinai approach?
@nakoale

**Comment by nakoale** [comment]
το TAR ειναι το terminal area radar οποτε συμφωνα με το aip το TAR ονομαζεται arrival στα inbounds και departure στα outbound. εξαλλου οι primary freq και για τους δυο σταθμους ειναι αυτες που εχουμε στo euroscope. το ATHINAI APP περιλαμβανει ολες τις εν δυναμει συχνοτητες (αν δεις μεσα ειναι και το arrival και το departure)

**Comment by tasosb** [comment]
@nakoale
Σωστα, αρα αν το Departure και το Director ειναι κλειστα, τo APP γινεται Athinai Approach

**Comment by nakoale** [comment]
μα δεν σε ενδιαφερει εσενα αυτο. στην πλειονοτητα των περιπτωσεων το APP και το DEP ειναι ανοιχτα. αλλου ειναι το point μου. οτι βασει του aip ΟΛΟ μαζι λεγεται ATHINAI APP (APPROACH) ειναι η προσεγγιση των Αθηνων η λεγομενη. η προσεγγιση λοιπον χωριζεται στις αφιξεις και στις αναχωρησεις. οι αφιξεις εχουν να κανουν με το arrival και οι αναχωρησεις με το departure. εξαλλου οι χαρτες το λενε ξεκαθαρα. τωρα σε λιγη κινηση κλεινει το departure και μενει το arrival. ο πυργος αν ειχαμε την δυνατοτητα να τον ακουσουμε σου λεει contact departure παροτι ειναι το 132.975 ανοιχτο. προφανως θα ηταν ηλιθιο να σου λεγεται καλεσε τις αφιξεις :P . Aρα λοιπον ολες οι συχνοτητες τις προσεγγισης Αθηνων απαρτιζουν το ΑPP και οι 2 γνωστες για αφιξεις και αναχωρησεις ειναι arrival και departure αντιστοιχα. και το DIRECTOR approach ειναι αλλα λεγεται director για να καταλαβουμε ποιο απο ολα τα appoaches ειναι και συνεπως τί ελεγχει. νομιζω τα ειπα οσο πιο αναλυτικα γινεται :P η μονη διαφορα με τον χαρτη και το aip ειναι το athens και το athina/athinai. το σωστοτερο ειναι athinai και τα την αποψη μου και αυτο εχω ακουσει να λενε. γιαυτο λες wien radar και οχι vienna, warsawa radar και οχι warsaw.
![Screenshot_1](https://user-images.githubusercontent.com/19704019/63596901-efdcd600-c5c4-11e9-93a8-4cf59e084d78.png)

**Comment by tasosb** [comment]
@nakoale
Ωραια, αρα μενει athinai arrival.
Βεβαια για το δικτυο και επειδη μονο app ειναι ανοιχτο συνηθως το athinai approach μπορει να ειναι καλυτερο.
