### ISSUE TITLE
[FIR COPX] bug EVIVI is shown as FIR copx but ATFIR is the FP exit point. 

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#54]
![Screenshot_2](https://user-images.githubusercontent.com/19704019/63021098-819f6180-bea8-11e9-9d34-467f7dc2dba6.png)
![Screenshot_3](https://user-images.githubusercontent.com/19704019/63021099-819f6180-bea8-11e9-98cd-f64f32b5b47d.png)

**Comment by tasosb** [comment]
Πρέπει να έχει φτιαχτεί τώρα.
notes:
![εικόνα](https://user-images.githubusercontent.com/18355854/63450996-ebd97880-c44b-11e9-8dba-a2a453f61618.png)
