### ISSUE TITLE
[GROUND LAYOUT] LGRP new stands according to FSDF new scenery

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#57]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you suggest**
A clear and concise description of what you want to change.

**Additional context**

**Comment by tasosb** [comment]
NEW:
![εικόνα](https://user-images.githubusercontent.com/18355854/64725553-7ce8c000-d4dd-11e9-8c14-38b14156f673.png)
