### ISSUE TITLE
[Other] CODIC Point added LGRP

### ISSUE THREAD

**Issue by tasosb** [tasosb/hvacc-sector-file#83]
**Description**
Check AIP 
SIDs
STARs
Enable waypoint on LGGGAPP asr
**Additional context**
Add any other context here.

**Comment by nakoale** [comment]
COPX for CODIC as for ASIMI

**Comment by tasosb** [comment]
COPX ok
LGGGAPP asr remains

**Comment by marks87** [comment]
FIXED LGRP QUICKVIS

**Comment by marks87** [comment]
LGGGAPP & LGRPAPP asr fixed
