### ISSUE TITLE
[GROUND] LGTS new taxilinks from 2003 airac

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#84]
**Description**

**Additional context**
Add any other context here.

**Comment by nakoale** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/19704019/75900268-5892ee00-5e45-11ea-82fa-c608b466a59e.png)

**Comment by tasosb** [comment]
stand μενουν τα ιδια μεχρι scenery update

**Comment by tasosb** [comment]
A0976/20 - REF AIP AIRAC AMDT 03/20 WEF 26 MAR 2020, PLEASE DISREGARD AD2-LGTS-APDC AND LGTS AD 2.20 LOCAL TRAFFIC REGULATIONS. 24 MAR 18:50 2020 UNTIL 15 APR 22:00 2020. CREATED: 24 MAR 18:53 2020

A0975/20 - REF AIP AIRAC AMDT 03/20 WED 26 MAR, AD2-LGTS-ADC CHANGES IN TWYS NAMING NOT APPLICABLE YET.  FOLLOW SIGNAGE IN PLACE AND ATC INSTRUCTIONS.  FOLLOW ME AVAILABLE UPON REQUEST. 24 MAR 18:07 2020 UNTIL 15 APR 22:00 2020. CREATED: 24 MAR 18:10 2020

**Comment by tasosb** [comment]
New taxilinks added, stands pending new scenery
to be added on ASR files
