### ISSUE TITLE
[BUG] LGKO Groundlayout Line Correction [***Reminder***]

### ISSUE THREAD

**Issue by Vasilis-Chalipilias** [tasosb/hvacc-sector-file#85]
**LGKO Groundlayout Line Correction**
Τασο το εβαλα για reminder μην το ξεχάσεις.

**Screenshots**
![lgko](https://user-images.githubusercontent.com/61604658/75928341-dc190300-5e76-11ea-9838-3ebc58918fb8.png)

**Comment by tasosb** [comment]
Fixed
