### ISSUE TITLE
[COPX] FIR COPX points (NEW) VANZA,OTHON,ANIDE. AGAPI,MAGIS,ABILO withdrawn

### ISSUE THREAD

**Issue by nakoale** [tasosb/hvacc-sector-file#92]
**Description**

**Additional context**
Add any other context here.

**Comment by tasosb** [comment]
Glo COPX fixed

**Comment by tasosb** [comment]
To be updated on: ALIAS, LGGG_CTR.asr

**Comment by marks87** [comment]
FIXED QUICKVIS

**Comment by marks87** [comment]
LGGG_CTR.asr ONLY

**Comment by marks87** [comment]
FIXED LGGG_CTR.asr , LGRP_APP.asr
